services:
  - type: web
    name: esk-estoic-api
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python -m uvicorn src.main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 8000
      - key: APP_ENV
        value: production
      - key: HOST
        value: 0.0.0.0
      - key: ALLOWED_ORIGINS
        value: '*'
    healthCheckPath: /health
    autoDeploy: true
