name: Deploy to Render

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    
    permissions:
      contents: read
      deployments: write
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      
      - name: Create .env file
        run: |
          echo "APP_ENV=production" >> .env
          echo "PORT=8000" >> .env
          echo "HOST=0.0.0.0" >> .env
          echo "ALLOWED_ORIGINS=https://estoicapi.com,https://www.estoicapi.com,https://app.estoicapi.com" >> .env
      
      - name: Deploy to Render
        uses: johnbeynon/render-deploy-action@v0.0.8
        with:
          service-id: ${{ secrets.RENDER_SERVICE_ID }}
          api-key: ${{ secrets.RENDER_API_KEY }}
