name: Deploy to GitHub Pages

on:
  push:
    branches: [ main ]
  workflow_run:
    workflows: ["Run Tests"]
    types:
      - completed
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' || github.event_name == 'push' }}
    
    permissions:
      contents: read
      pages: write
      id-token: write
      
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
      
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Pages
        uses: actions/configure-pages@v4
        
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          
      - name: Build static site
        run: |
          mkdir -p _site
          cp -r index.html static/ _site/
          if [ -n "${{ secrets.API_URL }}" ]; then
            echo "API_URL=${{ secrets.API_URL }}" > _site/.env
          else
            echo "API_URL=https://api.estoicismo.app" > _site/.env
          fi
          
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v3
